title: Jay Motamarry
description: Electrical Engineering & Computer Sciences Student at UC Berkeley
theme: jekyll-theme-minimal
logo: /assets/profile.jpg # You can add a profile picture later!
show_downloads: false
google_analytics: