title: Jay Motamarry's Portfolio
description: Software Engineer | Data Analyst | Creative Thinker
theme: jekyll-theme-minimal
logo: /assets/profile.jpg # You can add a profile picture later!
show_downloads: false # Hides the "Download ZIP" buttons to make it look like a website, not a repo
google_analytics: # UA-OIY-XXXXX (Optional: Add your ID here if you use GA)
